FROM dalibo/buildpack:bullseye

RUN set -ex; \
    apt-get update -y; \
    apt-get install -y --no-install-recommends python3-pip ; \
    apt-get clean; \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*; \
    pip3 --version; \
    :

ENV PIP_DISABLE_PIP_VERSION_CHECK 1
ENV PIP_NO_PYTHON_VERSION_WARNING 1
