FROM dalibo/buildpack:rockylinux10

RUN set -ex; \
    yum -q -y --disablerepo='pgdg*' install \
        cyrus-sasl-gssapi \
        cyrus-sasl-md5 \
        krb5-workstation \
        openldap-clients \
        python3 \
        python3-pip \
    ; \
    yum clean all ; \
    :

ENV PIP_DISABLE_PIP_VERSION_CHECK=1
ENV PIP_NO_PYTHON_VERSION_WARNING=1

COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/bin/
